version: "3.9"
services:
  server:
    build: .
    container_name: keeper-server
    ports:
      - '8082:8082'
    environment:
      DATABASE_URI: host=postgres-db user=myuser password=123456 dbname=SafeKeeper sslmode=disable
      HOST_ADDRESS: :8082
      STORAGE_DIR: "./Storage/"
    depends_on:
      - postgres-db
    networks:
      - keeper-network
  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: SafeKeeper
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    networks:
      - keeper-network
    # logging:
    #   driver: none
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d SafeKeeper" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

networks:
  keeper-network:
    name: keeper-network
    driver: bridge