FROM golang:1.24

WORKDIR /usr/src/server

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download

COPY . .
WORKDIR /usr/src/server/cmd/server
EXPOSE 8082
ENV HOST_ADDRESS=:8082

RUN go build -v -o /usr/local/bin/server ./...

ENTRYPOINT ["server"]